#ifndef ARENA_CONSTANTS_H
#define ARENA_CONSTANTS_H
/***
 * All constants defining the game logic (e.g. what are the players' stats, when do creeps spawn etc.)
 * are collected here. As a rule, there should be no constants related to the game logic outside of this
 * file.
 */

#define NETWORK_PORT 53000
#define MAX_NUM_PLAYERS 6
#define MAX_LIVES 40
#define SIMULATION_TIME_STEP_MS 100
#define SIMULATION_TIME_STEP_SEC (SIMULATION_TIME_STEP_MS / 1000.0)

#define DEFAULT_CHARACTER_RADIUS 0.25
#define DEFAULT_CHARACTER_ATTACK_RANGE 2

#define CREEP_STUCK_TIMER_MS 2000
#define PLAYER_RESPAWN_SEC 20
#define HEALING_ZONE_MAX_HP_PERCENTAGE_REGEN_SEC 5
#define HEALING_ZONE_MAX_MP_PERCENTAGE_REGEN_SEC 10
#define PLAYER_MAX_MP_PERCENTAGE_REGEN_SEC 2

#define CREEP_SPAWN_COOLDOWN_SEC 3
#define CREEP_SPAWN_POINT_2_ACTIVATE_MIN 3
#define CREEP_SPAWN_POINT_3_ACTIVATE_MIN 8
#define CREEP_SPAWN_POINT_HP 5000
#define CREEP_SPAWN_NEXT_LEVEL_SEC 90

#define XP_GOLD_PER_KILLED_CREEP 100

#define PLAYER_INITIAL_MAX_MOVEMENT_PER_SEC 3
#define PLAYER_KNIGHT_INITIAL_HP 50
#define PLAYER_ARCHER_INITIAL_HP 40
#define PLAYER_MAGE_INITIAL_HP 30
#define PLAYER_MONK_INITIAL_HP 45
#define PLAYER_KNIGHT_INITIAL_MP 20
#define PLAYER_ARCHER_INITIAL_MP 20
#define PLAYER_MAGE_INITIAL_MP 30        
#define PLAYER_MONK_INITIAL_MP 30
#define PLAYER_KNIGHT_INITIAL_ATTACK_COOLDOWN_MS 800
#define PLAYER_ARCHER_INITIAL_ATTACK_COOLDOWN_MS 700
#define PLAYER_MAGE_INITIAL_ATTACK_COOLDOWN_MS 1000
#define PLAYER_MONK_INITIAL_ATTACK_COOLDOWN_MS 1000
#define PLAYER_KNIGHT_INITIAL_ATTACK_DMG 4
#define PLAYER_ARCHER_INITIAL_ATTACK_DMG 4
#define PLAYER_MAGE_INITIAL_ATTACK_DMG 4
#define PLAYER_MONK_INITIAL_ATTACK_DMG 4
#define PLAYER_KNIGHT_ATTACK_RANGE DEFAULT_CHARACTER_ATTACK_RANGE
#define PLAYER_ARCHER_ATTACK_RANGE 10
#define PLAYER_MAGE_ATTACK_RANGE 6
#define PLAYER_MONK_ATTACK_RANGE 4

#define PLAYER_SKILL_BASE_COOLDOWN_SECONDS 10
#define PLAYER_ARCHER_DISTRACTION_DMG_FACTOR 1.3
#define PLAYER_ARCHER_DISTRACTION_MAX_DISTANCE_TO_ALLY 2
#define PLAYER_ARCHER_DISTRACTION_LEVELUP_DMG_FACTOR_ADD 0.2
#define PLAYER_ARCHER_DISTRACTION_MAX_LEVEL 5
#define PLAYER_ARCHER_MULTIARROW_RADIUS 4
#define PLAYER_ARCHER_MULTIARROW_COST_MP 8
#define PLAYER_ARCHER_MULTIARROW_MAX_LEVEL 1
#define PLAYER_ARCHER_COOLARROW_SECONDS 10
#define PLAYER_ARCHER_COOLARROW_COST_MP 4
#define PLAYER_ARCHER_COOLARROW_LEVELUP_EXTRA_SECONDS 5
#define PLAYER_ARCHER_COOLARROW_MAX_LEVEL 5
#define PLAYER_ARCHER_CREATE_SCARECROW_HP 20
#define PLAYER_ARCHER_CREATE_SCARECROW_COST_MP 15
#define PLAYER_ARCHER_CREATE_SCARECROW_MAX_LEVEL 6
#define PLAYER_ARCHER_CREATE_SCARECROW_LEVELUP_EXTRA_HP 20
#define PLAYER_ARCHER_POISON_VIAL_RADIUS 4
#define PLAYER_ARCHER_POISON_VIAL_DMG_PER_SEC 2
#define PLAYER_ARCHER_POISON_VIAL_SECONDS 8
#define PLAYER_ARCHER_POISON_VIAL_COST_MP 15
#define PLAYER_ARCHER_POISON_VIAL_MAX_LEVEL 5
#define PLAYER_ARCHER_POISON_VIAL_LEVELUP_EXTRA_SECONDS 4
#define PLAYER_ARCHER_POISON_VIAL_LEVELUP_EXTRA_DMG 1.5
#define PLAYER_KNIGHT_TANK_SECONDS 7
#define PLAYER_KNIGHT_TANK_COST_MP 10
#define PLAYER_KNIGHT_TANK_MAX_LEVEL 6
#define PLAYER_KNIGHT_TANK_LEVELUP_EXTRA_SECONDS 4
#define PLAYER_KNIGHT_CARNAGE_RADIUS 2
#define PLAYER_KNIGHT_CARNAGE_COST_MP 10
#define PLAYER_KNIGHT_CARNAGE_MAX_LEVEL 3
#define PLAYER_KNIGHT_CARNAGE_EXTRA_RADIUS 1
#define PLAYER_KNIGHT_MIGHT_FACTOR 6
#define PLAYER_KNIGHT_MIGHT_COST_MP 10
#define PLAYER_KNIGHT_MIGHT_MAX_LEVEL 5
#define PLAYER_KNIGHT_MIGHT_LEVELUP_EXTRA_FACTOR 3
#define PLAYER_KNIGHT_RAGE_ATTACK_COOLDOWN_FACTOR 0.5
#define PLAYER_KNIGHT_RAGE_SECONDS 6
#define PLAYER_KNIGHT_RAGE_COST_MP 15
#define PLAYER_KNIGHT_RAGE_MAX_LEVEL 5
#define PLAYER_KNIGHT_RAGE_LEVELUP_EXTRA_SECONDS 5
#define PLAYER_MAGE_FIREBALL_FACTOR 5
#define PLAYER_MAGE_FIREBALL_COST_MP 10
#define PLAYER_MAGE_FIREBALL_LEVELUP_EXTRA_FACTOR 2
#define PLAYER_MAGE_FIREBALL_MAX_LEVEL 5
#define PLAYER_MAGE_DEATHZONE_FACTOR 0.3
#define PLAYER_MAGE_DEATHZONE_SECONDS 7
#define PLAYER_MAGE_DEATHZONE_RADIUS 5
#define PLAYER_MAGE_DEATHZONE_COOLDOWN_FACTOR 4
#define PLAYER_MAGE_DEATHZONE_COST_MP 20
#define PLAYER_MAGE_DEATHZONE_MAX_LEVEL 4
#define PLAYER_MAGE_DEATHZONE_LEVELUP_EXTRA_SECONDS 5
#define PLAYER_MAGE_ICEBOMB_FACTOR 2
#define PLAYER_MAGE_ICEBOMB_RADIUS 3
#define PLAYER_MAGE_ICEBOMB_SECONDS 8
#define PLAYER_MAGE_ICEBOMB_COST_MP 15
#define PLAYER_MAGE_ICEBOMB_EXTRA_SECONDS 5
#define PLAYER_MAGE_ICEBOMB_MAX_LEVEL 5
#define PLAYER_MAGE_CONFUSE_RADIUS 4
#define PLAYER_MAGE_CONFUSE_SECONDS 8
#define PLAYER_MAGE_CONFUSE_COST_MP 15
#define PLAYER_MAGE_CONFUSE_LEVELUP_EXTRA_SECONDS 5
#define PLAYER_MAGE_CONFUSE_MAX_LEVEL 5
#define PLAYER_MONK_HEAL_HP 15
#define PLAYER_MONK_HEAL_XP 100
#define PLAYER_MONK_HEAL_COST_MP 10
#define PLAYER_MONK_HEAL_MAX_LEVEL 6
#define PLAYER_MONK_HEAL_LEVELUP_EXTRA_HP 10
#define PLAYER_MONK_DEATHZONE_FACTOR 0.2
#define PLAYER_MONK_DEATHZONE_SECONDS 12
#define PLAYER_MONK_DEATHZONE_RADIUS 5
#define PLAYER_MONK_DEATHZONE_COOLDOWN_FACTOR 4
#define PLAYER_MONK_DEATHZONE_COST_MP 20
#define PLAYER_MONK_DEATHZONE_MAX_LEVEL 4
#define PLAYER_MONK_DEATHZONE_LEVELUP_EXTRA_SECONDS 5
#define PLAYER_MONK_TELEPORT_COST_MP 15
#define PLAYER_MONK_TELEPORT_MAX_LEVEL 1
#define PLAYER_MONK_MASS_HEAL_HP 10
#define PLAYER_MONK_MASS_HEAL_XP 100
#define PLAYER_MONK_MASS_HEAL_COST_MP 20
#define PLAYER_MONK_MASS_HEAL_MAX_LEVEL 6
#define PLAYER_MONK_MASS_HEAL_LEVELUP_EXTRA_HP 8

#define LEVELUP_HP_FACTOR 1.3
#define LEVELUP_MP_FACTOR 1.3
#define LEVELUP_ATTACK_COOLDOWN_FACTOR 0.9
#define LEVELUP_ATTACK_DMG_FACTOR 1.2

#define DEFAULT_CREEP_SEEK_RANGE 4
#define DEFAULT_CREEP_MAX_MOVEMENT_PER_SEC 2
#define CREEP_INITIAL_HP 12
#define CREEP_INITIAL_ATTACK_COOLDOWN_MS 1200
#define CREEP_INITIAL_ATTACK_DMG 0.7

#define SHOP_COST_HP_POTION 500
#define SHOP_COST_MP_POTION 400
#define SHOP_COST_HP_TOME 1000
#define SHOP_COST_MP_TOME 1000
#define SHOP_COST_XP_TOME 1000
#define SHOP_COST_MOVEMENT_TOME 1500
#define SHOP_COST_ATTACK_COOLDOWN_TOME 2000
#define SHOP_COST_ATTACK_DAMAGE_TOME 4000
#define SHOP_COST_SKILL_COOLDOWN_TOME 4000

#define ITEM_HP_POTION_HP_GAIN 30
#define ITEM_MP_POTION_MP_GAIN 30
#define ITEM_HP_TOME_MAX_HP_INCREASE 15
#define ITEM_MP_TOME_MAX_MP_INCREASE 15
#define ITEM_XP_TOME_XP_GAIN 1000
#define ITEM_MOVEMENT_TOME_MOVEMENT_GAIN 1
#define ITEM_ATTACK_COOLDOWN_TOME_FACTOR 0.8
#define ITEM_ATTACK_DAMAGE_TOME_FACTOR 1.3
#define ITEM_SKILL_COOLDOWN_TOME_FACTOR 0.8

#define ARCHER_ATTACK_ANIMATION_SHOOT_STEP 5

#endif     
